disabled_rules:
    - variable_name
    - type_body_length
    - file_length
    - trailing_whitespace

included: # paths to include during linting. `--path` is ignored if present.
  - SWSG
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length: 120
